/* eslint-disable @next/next/link-passhref */
/* eslint-disable @next/next/no-img-element */
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Blogs/Card-design-2'
import Header from '../components/Home/Header/Header'
import styles from '../styles/Home.module.css'
import { images, posts, animations } from '../assets/constants'

const carLightsOff = '../static/images/car.png'
const carLightsOn = '../static/images/car-lights-on.png'

function Home (props) {
  const [carOn, setCarOn] = useState(true)

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <section className={styles.hero}>
        <div className='mx-auto flex h-full flex-col items-center relative backgroundImage'>
          {/* <div className='flex flex-col h-full w-full items-center relative'> */}
          <Image
            src='../static/images/Starry.jpg'
            // src={'https://source.unsplash.com/random/800x600'}
            alt=''
            title=''
            width='100%'
            height='100%'
            layout='responsive'
            // loader={myLoader}
            unoptimized={true}
            objectFit='cover'
          />
          <div className='container mx-auto w-full h-full relative'>
            <div className='w-fit absolute  top-[50%] translate-y-[-50%] md:translate-y-[0%] md:top-[22%] left-0 right-0 bg-opacity-30 bg-black p-8 rounded-md mx-4'>
              <h1 className='text-5xl font-bold text-white mb-3'>
                Time to get your house clean
              </h1>
              <h1 className='text-5xl font-bold text-white'>
                Clean and in order
              </h1>
              <p className='text-gray-200 text-lg mt-4'>
                To have good air quality is not as simple as moving away from
                the city to a
              </p>
              <p className='text-gray-200 text-lg '>
                quiet suburb or rural environment
              </p>

              <button className='border-solid border-1 bg-blue-500 border-sky-500 w-fit py-1 px-4 rounded-md mt-8 my-4 text-md text-white'>
                Read Article
              </button>
            </div>
          </div>
        </div>
        {/* </div> */}
      </section>

      <div className='container gap-4 w-full py-10 px-4 mx-auto flex-row flex items-start'>
        <div className='grid grid-cols-1 md:grid-cols-2  gap-4 items-start'>
          {posts?.slice(0, 2).map((item, index) => (
            <Card key={item.id} post={item} showImage={true} charLength={150} />
          ))}
        </div>
        <div className='sm:d-none gap-y-4 hidden sm:flex flex-col '>
          {posts?.slice(1, 4).map((item, index) => (
            <Card
              key={item.id}
              post={item}
              charLength={100}
              size='sm'
              buttonType='linkTag'
            />
          ))}
        </div>
      </div>

      <div className='container mx-auto flex justify-between w-88 px-4 items-center'>
        <h3 style={{ color: '#0d1063' }} className='text-3xl font-semibold'>
          The Science behind SmartUV
        </h3>
        <button className='border-solid border-2 border-sky-500 w-fit py-1 px-4 rounded-md my-2 text-sm text-sky-500'>
          Read Article
        </button>
      </div>

      <div className='container py-4 px-4 gap-4 grid-cols-1 md:grid-cols-2  lg:grid-cols-4 grid  w-88 mx-auto items-start'>
        {posts?.map((item, index) => (
          <Card
            key={item.id + `- ${index}`}
            post={item}
            showImage={true}
            buttonType='linkTag'
          />
        ))}
      </div>
      <div className={`${styles.animatedCar} mt-4`}>
        <div className={styles.sky}>
          <div className={styles.surface}></div>

          <img
            className={styles.car}
            onClick={() => setCarOn(!carOn)}
            src={carOn ? carLightsOn : carLightsOff}
            alt='car'
            // loader={myLoader}
          />
        </div>
      </div>
      <div className='container py-10 px-4 gap-4 grid-rows-4 md:grid-rows-3 grid-cols-1 md:grid-cols-3 hidden  md:grid mt-4 w-88 mx-auto '>
        <div className='gap-4 grid-cols-1 md:grid-cols-1 row-span-3  flex flex-col md:grid '>
          {posts?.slice(0, 3).map((item, index) => (
            <div
              className={`row-span-[${index + 1}] flex flex-1`}
              key={item.id + `- ${index}`}
            >
              <Card
                key={item.id + `- ${index}`}
                post={item}
                buttonType='linkTag'
              />
            </div>
          ))}
        </div>
        <div className='gap-4 grid-cols-1 md:grid-cols-1 col-span-2 row-span-3  grid  items-start'>
          {posts?.slice(3, 4).map((item, index) => (
            <Card
              key={item.id + `- ${index}`}
              post={item}
              showImage={true}
              buttonType='linkTag'
              noText={true}
            />
          ))}
        </div>
      </div>
  
    </div>
  )
}

export default Home
